# In-vehicle Coupon Recommendation  System With ANN

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
dataset = pd.read_csv('datasetrcouponrec.csv')

In [4]:
dataset.head()

destination  passanger weather  temperature  time  \
0  No Urgent Place      Alone   Sunny           55   2PM   
1  No Urgent Place  Friend(s)   Sunny           80  10AM   
2  No Urgent Place  Friend(s)   Sunny           80  10AM   
3  No Urgent Place  Friend(s)   Sunny           80   2PM   
4  No Urgent Place  Friend(s)   Sunny           80   2PM   

                  coupon expiration  gender age      maritalStatus  ...  \
0        Restaurant(<20)         1d  Female  21  Unmarried partner  ...   
1           Coffee House         2h  Female  21  Unmarried partner  ...   
2  Carry out & Take away         2h  Female  21  Unmarried partner  ...   
3           Coffee House         2h  Female  21  Unmarried partner  ...   
4           Coffee House         1d  Female  21  Unmarried partner  ...   

   CoffeeHouse CarryAway RestaurantLessThan20 Restaurant20To50  \
0        never       NaN                  4~8              1~3   
1        never       NaN                  4~8              1~3   
2        never       NaN                  4~8              1~3   
3        never       NaN                  4~8              1~3   
4        never       NaN                  4~8              1~3   

  toCoupon_GEQ5min toCoupon_GEQ15min toCoupon_GEQ25min direction_same  \
0                1                 0                 0              0   
1                1                 0                 0              0   
2                1                 1                 0              0   
3                1                 1                 0              0   
4                1                 1                 0              0   

  direction_opp  Y  
0             1  1  
1             1  0  
2             1  1  
3             1  0  
4             1  0  

[5 rows x 26 columns]

In [5]:
X = dataset.drop(labels=['destination', 'passanger','time','temperature','toCoupon_GEQ5min','weather','Y','car','Bar','CoffeeHouse','CarryAway','RestaurantLessThan20','Restaurant20To50'], axis = 1)
y = dataset['Y']

In [6]:
X.head()

coupon expiration  gender age      maritalStatus  \
0        Restaurant(<20)         1d  Female  21  Unmarried partner   
1           Coffee House         2h  Female  21  Unmarried partner   
2  Carry out & Take away         2h  Female  21  Unmarried partner   
3           Coffee House         2h  Female  21  Unmarried partner   
4           Coffee House         1d  Female  21  Unmarried partner   

   has_children                 education  occupation           income  \
0             1  Some college - no degree  Unemployed  $37500 - $49999   
1             1  Some college - no degree  Unemployed  $37500 - $49999   
2             1  Some college - no degree  Unemployed  $37500 - $49999   
3             1  Some college - no degree  Unemployed  $37500 - $49999   
4             1  Some college - no degree  Unemployed  $37500 - $49999   

   toCoupon_GEQ15min  toCoupon_GEQ25min  direction_same  direction_opp  
0                  0                  0               0              1  
1                  0                  0               0              1  
2                  1                  0               0              1  
3                  1                  0               0              1  
4                  1                  0               0              1

In [7]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Y, dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
label1 = LabelEncoder()
X['maritalStatus'] = label1.fit_transform(X['maritalStatus'])

In [10]:
X.head()

coupon expiration  gender age  maritalStatus  has_children  \
0        Restaurant(<20)         1d  Female  21              3             1   
1           Coffee House         2h  Female  21              3             1   
2  Carry out & Take away         2h  Female  21              3             1   
3           Coffee House         2h  Female  21              3             1   
4           Coffee House         1d  Female  21              3             1   

                  education  occupation           income  toCoupon_GEQ15min  \
0  Some college - no degree  Unemployed  $37500 - $49999                  0   
1  Some college - no degree  Unemployed  $37500 - $49999                  0   
2  Some college - no degree  Unemployed  $37500 - $49999                  1   
3  Some college - no degree  Unemployed  $37500 - $49999                  1   
4  Some college - no degree  Unemployed  $37500 - $49999                  1   

   toCoupon_GEQ25min  direction_same  direction_opp  
0                  0               0              1  
1                  0               0              1  
2                  0               0              1  
3                  0               0              1  
4                  0               0              1

In [11]:
label = LabelEncoder()
X['gender'] = label.fit_transform(X['gender'])
X.head()

coupon expiration  gender age  maritalStatus  has_children  \
0        Restaurant(<20)         1d       0  21              3             1   
1           Coffee House         2h       0  21              3             1   
2  Carry out & Take away         2h       0  21              3             1   
3           Coffee House         2h       0  21              3             1   
4           Coffee House         1d       0  21              3             1   

                  education  occupation           income  toCoupon_GEQ15min  \
0  Some college - no degree  Unemployed  $37500 - $49999                  0   
1  Some college - no degree  Unemployed  $37500 - $49999                  0   
2  Some college - no degree  Unemployed  $37500 - $49999                  1   
3  Some college - no degree  Unemployed  $37500 - $49999                  1   
4  Some college - no degree  Unemployed  $37500 - $49999                  1   

   toCoupon_GEQ25min  direction_same  direction_opp  
0                  0               0              1  
1                  0               0              1  
2                  0               0              1  
3                  0               0              1  
4                  0               0              1

In [12]:
label = LabelEncoder()
X['coupon'] = label.fit_transform(X['coupon'])
X['occupation'] = label.fit_transform(X['occupation'])
X['expiration'] = label.fit_transform(X['expiration'])
X['income'] = label.fit_transform(X['income'])
X['age'] = label.fit_transform(X['age'])
X['education'] = label.fit_transform(X['education'])
X.head(20)


coupon  expiration  gender  age  maritalStatus  has_children  education  \
0        4           0       0    0              3             1          5   
1        2           1       0    0              3             1          5   
2        1           1       0    0              3             1          5   
3        2           1       0    0              3             1          5   
4        2           0       0    0              3             1          5   
5        4           1       0    0              3             1          5   
6        1           0       0    0              3             1          5   
7        4           1       0    0              3             1          5   
8        1           1       0    0              3             1          5   
9        0           0       0    0              3             1          5   
10       4           0       0    0              3             1          5   
11       4           0       0    0              3             1          5   
12       2           1       0    0              3             1          5   
13       0           0       0    0              3             1          5   
14       3           0       0    0              3             1          5   
15       2           1       0    0              3             1          5   
16       2           1       0    0              3             1          5   
17       0           0       0    0              3             1          5   
18       3           0       0    0              3             1          5   
19       1           1       0    0              3             1          5   

    occupation  income  toCoupon_GEQ15min  toCoupon_GEQ25min  direction_same  \
0           24       3                  0                  0               0   
1           24       3                  0                  0               0   
2           24       3                  1                  0               0   
3           24       3                  1                  0               0   
4           24       3                  1                  0               0   
5           24       3                  1                  0               0   
6           24       3                  1                  0               0   
7           24       3                  1                  0               0   
8           24       3                  1                  0               0   
9           24       3                  1                  0               0   
10          24       3                  0                  0               0   
11          24       3                  1                  0               0   
12          24       3                  1                  0               0   
13          24       3                  0                  0               1   
14          24       3                  1                  0               0   
15          24       3                  0                  0               0   
16          24       3                  1                  1               0   
17          24       3                  1                  1               0   
18          24       3                  1                  0               0   
19          24       3                  0                  0               1   

    direction_opp  
0               1  
1               1  
2               1  
3               1  
4               1  
5               1  
6               1  
7               1  
8               1  
9               1  
10              1  
11              1  
12              1  
13              0  
14              1  
15              1  
16              1  
17              1  
18              1  
19              0

### Feature Standardization 

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 10)

In [15]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [16]:
X_train

array([[-0.02944168, -0.88701501, -0.97627569, ..., -0.36561085,
        -0.53025457,  0.53025457],
       [-1.51428103, -0.88701501,  1.02430083, ...,  2.73514861,
        -0.53025457,  0.53025457],
       [ 1.45539766, -0.88701501, -0.97627569, ..., -0.36561085,
        -0.53025457,  0.53025457],
       ...,
       [-0.77186136,  1.12737664, -0.97627569, ..., -0.36561085,
         1.88588663, -1.88588663],
       [-0.77186136,  1.12737664,  1.02430083, ..., -0.36561085,
        -0.53025457,  0.53025457],
       [ 0.71297799, -0.88701501,  1.02430083, ..., -0.36561085,
        -0.53025457,  0.53025457]])

### Build ANN 

In [17]:
model = Sequential()
model.add(Dense(X.shape[1], activation='relu', input_dim = X.shape[1]))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [18]:
X.shape[1]

13

In [19]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [20]:
model.fit(X_train, y_train.to_numpy(), batch_size = 32, epochs = 1000, verbose = 1)

Epoch 1/10
266/266 [==============================] - 0s 801us/step - loss: 0.6709 - accuracy: 0.5931
Epoch 2/10
266/266 [==============================] - 0s 797us/step - loss: 0.6574 - accuracy: 0.6099
Epoch 3/10
266/266 [==============================] - 0s 826us/step - loss: 0.6527 - accuracy: 0.6088
Epoch 4/10
266/266 [==============================] - 0s 769us/step - loss: 0.6493 - accuracy: 0.6141
Epoch 5/10
266/266 [==============================] - 0s 808us/step - loss: 0.6460 - accuracy: 0.6229
Epoch 6/10
266/266 [==============================] - 0s 813us/step - loss: 0.6450 - accuracy: 0.6237
Epoch 7/10
266/266 [==============================] - 0s 774us/step - loss: 0.6422 - accuracy: 0.6245
Epoch 8/10
266/266 [==============================] - 0s 788us/step - loss: 0.6390 - accuracy: 0.6330
Epoch 9/10
266/266 [==============================] - 0s 739us/step - loss: 0.6353 - accuracy: 0.6340
Epoch 10/10
266/266 [==============================] - 0s 768us/step - loss: 0.632

In [28]:
y_pred = model.predict_classes(X_test)

In [29]:
y_pred

array([[0],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [30]:
y_test

3868     0
1829     1
11519    1
8659     1
4646     0
        ..
1756     1
12290    1
9718     1
9024     1
1061     1
Name: Y, Length: 4186, dtype: int64

In [31]:
model.evaluate(X_test, y_test.to_numpy())

131/131 [==============================] - 0s 695us/step - loss: 0.6440 - accuracy: 0.6237


[0.6439911127090454, 0.6237457990646362]

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [33]:
confusion_matrix(y_test, y_pred)

array([[ 875,  990],
       [ 585, 1736]], dtype=int64)

In [34]:
accuracy_score(y_test, y_pred)

0.6237458193979933